import { useState } from 'react'
import { Download, Sparkles } from 'lucide-react'
import { generateAiAnnualDocument } from '../data/api'
import { downloadHtmlPdf } from '../data/pdf'
import ydmLogo from '../assets/jsc-ydm-logo-certificate.png'

type Kind = 'yearly' | 'welcome' | 'thanks'
const titles: Record<Kind, string> = { yearly: 'Yearly ministry report', welcome: 'Year welcome speech', thanks: 'Vote of thanks' }
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character] || character)

export default function AdminAiAnnualDocuments() {
  const [kind, setKind] = useState<Kind>('yearly')
  const [year, setYear] = useState(String(new Date().getFullYear()))
  const [language, setLanguage] = useState<'en' | 'ta'>('en')
  const [draft, setDraft] = useState('')
  const [busy, setBusy] = useState(false)
  const [status, setStatus] = useState('')
  const generate = async () => { setBusy(true); setStatus('Creating an AI draft from saved annual ministry totals…'); try { const result = await generateAiAnnualDocument(kind, year, language); setDraft(result.answer); setStatus('AI draft created. Review or edit it before downloading.') } catch { setStatus('AI draft could not be created. Check the Gemini server key and try again.') } finally { setBusy(false) } }
  const download = async () => { if (!draft.trim()) return; setBusy(true); try { const paragraphs = draft.split(/\n\s*\n/).map(item => `<p>${escapeHtml(item)}</p>`).join(''); const html = `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4 portrait;margin:14mm}body{font-family:Arial,sans-serif;color:#172b24}.page{border:2px solid #e3bc62;padding:36px}.logo{display:block;width:72px;height:72px;object-fit:contain;margin:auto}header{text-align:center;border-bottom:1px solid #c7dfd4;padding-bottom:18px}.eyebrow{color:#087f5b;font-size:11px;font-weight:bold;letter-spacing:2px;text-transform:uppercase}h1{font:700 30px Georgia,serif}.content{font-size:14px;line-height:1.75;text-align:justify}.content p{margin:0 0 14px}</style></head><body><main class="page"><header><img class="logo" src="${ydmLogo}" alt="YDM logo"><p class="eyebrow">Jehovah Salvation Church · Youth Divine Movement</p><h1>${titles[kind]} · ${year}</h1></header><section class="content">${paragraphs}</section></main></body></html>`; await downloadHtmlPdf(html, `jsc-ydm-ai-${kind}-${year}-${language}.pdf`); setStatus('AI document PDF downloaded.') } catch { setStatus('The PDF could not be created. Please try again.') } finally { setBusy(false) } }
  return <section className="soft-card mt-6"><div className="flex items-start gap-3"><span className="icon-box"><Sparkles size={20} /></span><div><p className="eyebrow">Admin AI writer</p><h2 className="mt-1 text-xl font-black">AI generated annual documents</h2><p className="mt-1 text-sm text-slate-500">Uses selected-year aggregate ministry data only. Review the draft before download.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="field-label">Document<select className="field" value={kind} onChange={event => setKind(event.target.value as Kind)}>{Object.entries(titles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field-label">Year<input className="field" value={year} inputMode="numeric" maxLength={4} onChange={event => setYear(event.target.value.replace(/\D/g, ''))} /></label><label className="field-label">Language<select className="field" value={language} onChange={event => setLanguage(event.target.value as 'en' | 'ta')}><option value="en">English</option><option value="ta">Tamil</option></select></label></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="primary-btn" disabled={busy || !/^\d{4}$/.test(year)} onClick={() => void generate()}><Sparkles size={17} /> {busy ? 'Generating…' : 'AI Generated'}</button>{draft && <button type="button" className="secondary-dark-btn" disabled={busy} onClick={() => void download()}><Download size={17} /> Download PDF</button>}</div>{draft && <label className="field-label mt-5">Editable AI draft<textarea className="field mt-1 min-h-[26rem] resize-none leading-7" value={draft} onChange={event => setDraft(event.target.value)} /></label>}{status && <p role="status" className="mt-4 text-sm font-semibold text-emerald-800">{status}</p>}</section>
}
