import { useEffect, useState } from 'react'
import { Download } from 'lucide-react'
import { getMembers } from '../data/api'
import { Member } from '../data/memberStore'

const esc = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
const roleRank = (role: string) => { const normalized = role.trim().toLowerCase().replace(/^ydm\s+/, ''); if (normalized.includes('vice president')) return 1; if (normalized.includes('president')) return 0; const roles = ['secretary', 'joint secretary', 'treasury', 'advisor', 'elder', 'member']; const match = roles.findIndex(item => normalized.includes(item)); return match === -1 ? roles.length + 1 : match + 2 }
const seniorityRank = (seniority: Member['seniority']) => seniority === 'Senior' ? 0 : seniority === 'Junior' ? 1 : seniority === 'Kutties' ? 2 : 3
const genderRank = (gender: string) => gender.trim().toLowerCase() === 'male' ? 0 : gender.trim().toLowerCase() === 'female' ? 1 : 2
const orderedMembers = (members: Member[]) => [...members].sort((a, b) => roleRank(a.role) - roleRank(b.role) || genderRank(a.gender) - genderRank(b.gender) || a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }) || seniorityRank(a.seniority) - seniorityRank(b.seniority))
const addGeneratedOn = (html: string) => html.replace('</header>', `<p style="position:absolute;right:18px;top:18px;margin:0;font-size:12px">Generated on ${new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}</p></header>`)
const fixSignatureFooter = (html: string) => html.replace('<div class="presidents">YDM President 1<br>YDM President 2</div>', '<div class="president-signatures" style="font-size:12px;line-height:1.5"><div>Signature,</div><div style="margin-top:8px">1. YDM President 1 -----------------</div><div style="margin-top:8px">2. YDM President 2 -----------------</div></div>')
const finalizeReportLayout = (html: string) => html.replace('</style>', '.signatures{position:static!important;margin-top:28px;break-inside:avoid;page-break-inside:avoid}@media print{@page{margin:0}body{padding:12mm 10mm 12mm}header{margin-bottom:14px}table{font-size:9px}th,td{padding:4px}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.signatures{position:static!important;margin-top:22px}}</style>')
const report = (members: Member[]) => `<html><head><meta charset="utf-8"><title>JSC YDM Member Details</title><style>@page{margin:18mm 14mm 25mm}body{font-family:Arial;padding:8px 18px 90px;color:#071f19}header{text-align:center;margin-bottom:24px}header .blessing{font-size:13px;margin:0 0 5px}header .church{font-size:20px;font-weight:700;margin:0 0 5px}header .report-title{font-size:13px;margin:0}h1{color:#087f5b}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #cbd5e1;padding:7px;text-align:left}th{background:#e8f5ef}.signatures{position:fixed;bottom:0;left:0;right:0;display:flex;justify-content:space-between;align-items:flex-end;font-size:12px;padding:10px 18px 0;background:#fff}.presidents{line-height:1.5;font-size:0}.presidents:before{content:'Signature,\\A 1) YDM President 1 -----------------\\A 2) YDM President 2 -----------------';white-space:pre;font-size:12px}.pastor{text-align:right;min-width:170px}.signature-line{border-top:1px solid #071f19;margin-top:28px;padding-top:4px}@media print{.signatures{position:fixed}}</style></head><body><header><p class="blessing">கர்த்தருக்கு ஸ்தோத்திரம்</p><p class="church">JSC YDM Kollemcode</p><p class="report-title">2026 - Member details</p></header><h1>Member Details</h1><table><thead><tr><th>Name</th><th>Role</th><th>Seniority</th><th>Gender</th><th>Email</th><th>Phone</th><th>Address</th><th>Date of birth</th><th>Focus</th></tr></thead><tbody>${members.map(m => `<tr><td>${esc(m.name)}</td><td>${esc(m.role)}</td><td>${esc(m.seniority || '')}</td><td>${esc(m.gender)}</td><td>${esc(m.email)}</td><td>${esc(m.phone)}</td><td>${esc(m.address)}</td><td>${esc(m.dateOfBirth)}</td><td>${esc(m.focus)}</td></tr>`).join('')}</tbody></table><footer class="signatures"><div class="presidents">YDM President 1<br>YDM President 2</div><div class="pastor"><div class="signature-line">Pastor Signature</div></div></footer></body></html>`
export default function AdminMemberExport() {
  const [members, setMembers] = useState<Member[]>([]); const [format, setFormat] = useState('pdf'); const [message, setMessage] = useState('')
  useEffect(() => { void getMembers().then(setMembers).catch(() => setMessage('Could not load member data.')) }, [])
  const download = () => { if (!members.length) { setMessage('No saved members to download.'); return }; const html = finalizeReportLayout(fixSignatureFooter(addGeneratedOn(report(orderedMembers(members))))); if (format === 'word') { const url = URL.createObjectURL(new Blob([html], { type: 'application/msword' })); const link = document.createElement('a'); link.href = url; link.download = 'jsc-ydm-member-details.doc'; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); return }; const printWindow = window.open('', '_blank'); if (!printWindow) { setMessage('Please allow pop-ups to create the PDF.'); return }; printWindow.document.open(); printWindow.document.write(html); printWindow.document.close(); try { printWindow.history.replaceState(null, '', '/admin/reports/jsc-ydm-member-details') } catch { /* The print document still remains free of Blob URLs. */ } setTimeout(() => { printWindow.focus(); printWindow.print() }, 150) }
  return <section className="soft-card admin-member-export mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Download member details</h2><p className="mt-1 text-sm text-slate-500">Private Admin report · {members.length} saved members</p></div><div className="flex flex-wrap gap-2"><select aria-label="Download format" className="field" value={format} onChange={event => setFormat(event.target.value)}><option value="pdf">PDF</option><option value="word">Word</option></select><button className="primary-btn" onClick={download}><Download size={17} /> Download</button></div></div>{message && <p className="mt-3 text-sm text-rose-700">{message}</p>}</section>
}
