import { useEffect, useMemo, useState } from 'react'
import { CreditCard, Download, RefreshCw } from 'lucide-react'
import { getMembers } from '../data/api'
import type { Member } from '../data/memberStore'
import ydmLogo from '../assets/jsc-ydm-logo-certificate.png'

const cardCss = `
.ydm-member-card{container-type:inline-size;position:relative;isolation:isolate;display:grid;grid-template-rows:auto 1fr auto;aspect-ratio:1.586/1;min-width:420px;overflow:hidden;border-radius:20px;border:1px solid rgba(227,188,98,.7);background:linear-gradient(130deg,#071f19 0%,#0d3428 58%,#12634b 100%);color:#fff;box-shadow:0 14px 30px rgba(4,21,17,.22)}
.ydm-member-card:before,.ydm-member-card:after{content:'';position:absolute;z-index:-1;pointer-events:none;border-radius:50%;border:1px solid rgba(227,188,98,.3)}
.ydm-member-card:before{width:68%;aspect-ratio:1;right:-32%;top:-42%}.ydm-member-card:after{width:55%;aspect-ratio:1;left:-28%;bottom:-50%;border-color:rgba(255,255,255,.12)}
.ydm-card-top{display:flex;align-items:center;justify-content:space-between;padding:5.5cqw 7cqw 0}.ydm-card-brand{display:flex;align-items:center;gap:2.8cqw}.ydm-card-logo{width:12cqw;height:12cqw;object-fit:contain}.ydm-card-overline{margin:0;color:#e3bc62;font:800 2.3cqw Arial,sans-serif;letter-spacing:.18em;text-transform:uppercase}.ydm-card-subtitle{margin:.7cqw 0 0;color:rgba(255,255,255,.64);font:1.65cqw Arial,sans-serif;letter-spacing:.06em}.ydm-card-chip{height:4.8cqw;width:7cqw;border:1px solid rgba(227,188,98,.75);border-radius:1cqw;background:linear-gradient(135deg,#e3bc62,#fff0b6);box-shadow:inset 0 0 0 1px rgba(7,31,25,.2)}
.ydm-card-main{display:flex;align-items:center;gap:5cqw;padding:0 7cqw}.ydm-card-photo{width:22cqw;height:22cqw;flex:none;border:2px solid #e3bc62;border-radius:50%;background:#e8f5ef;object-fit:cover}.ydm-card-initials{display:grid;place-items:center;color:#071f19;font:800 7cqw Arial,sans-serif}.ydm-card-label{margin:0;color:rgba(255,255,255,.58);font:700 1.6cqw Arial,sans-serif;letter-spacing:.1em;text-transform:uppercase}.ydm-card-name{margin:.8cqw 0 0;color:#fff;font:800 5cqw Georgia,'Times New Roman',serif;line-height:1.05;overflow-wrap:anywhere}.ydm-card-role{margin:1cqw 0 0;color:#e3bc62;font:700 2.2cqw Arial,sans-serif}.ydm-card-meta{margin:.8cqw 0 0;color:rgba(255,255,255,.7);font:1.7cqw Arial,sans-serif}.ydm-card-bottom{display:flex;justify-content:space-between;align-items:flex-end;padding:0 7cqw 5.5cqw}.ydm-card-id{color:rgba(255,255,255,.66);font:700 1.55cqw Arial,sans-serif;letter-spacing:.12em}.ydm-card-valid{color:#e3bc62;font:700 1.55cqw Arial,sans-serif;letter-spacing:.11em;text-transform:uppercase}
@media print{html,body{margin:0!important;padding:0!important;background:#fff!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.ydm-member-card{width:85.6mm;height:54mm;min-width:0;aspect-ratio:auto;break-inside:avoid}}
`

const escapeHtml = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
const memberNumber = (member: Member) => `YDM-${member.id.replace(/[^a-z0-9]/gi, '').slice(-8).toUpperCase().padStart(8, '0')}`
const initials = (name: string) => name.split(/\s+/u).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase()

export function membershipCardMarkup(member: Member) {
  const identity = member.photo ? `<img class="ydm-card-photo" src="${escapeHtml(member.photo)}" alt="${escapeHtml(member.name)}">` : `<div class="ydm-card-photo ydm-card-initials" aria-label="${escapeHtml(member.name)} initials">${escapeHtml(initials(member.name))}</div>`
  return `<article class="ydm-member-card" aria-label="YDM membership card for ${escapeHtml(member.name)}"><header class="ydm-card-top"><div class="ydm-card-brand"><img class="ydm-card-logo" src="${escapeHtml(ydmLogo)}" alt="YDM logo"><div><p class="ydm-card-overline">JSC YDM</p><p class="ydm-card-subtitle">Youth Divine Movement</p></div></div><span class="ydm-card-chip" aria-hidden="true"></span></header><div class="ydm-card-main">${identity}<div><p class="ydm-card-label">Member</p><h2 class="ydm-card-name">${escapeHtml(member.name)}</h2><p class="ydm-card-meta">${escapeHtml(member.gender || 'YDM')}</p></div></div><footer class="ydm-card-bottom"><span class="ydm-card-id">${memberNumber(member)}</span><span class="ydm-card-valid">Official Member</span></footer></article>`
}

export function membershipCardDocument(member: Member) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(member.name)} · YDM Membership Card</title><style>@page{size:85.6mm 54mm;margin:0}*{box-sizing:border-box}body{margin:0;background:#fff}${cardCss}</style></head><body>${membershipCardMarkup(member)}</body></html>`
}

export default function AdminMembershipCards() {
  const [members, setMembers] = useState<Member[]>([])
  const [selectedId, setSelectedId] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const refresh = async () => { setLoading(true); setError(''); try { setMembers(await getMembers()) } catch { setMembers([]); setSelectedId(''); setError('Could not load saved members. Check the connection and try again.') } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [])
  const sortedMembers = useMemo(() => [...members].sort((a, b) => a.name.localeCompare(b.name)), [members])
  const selected = sortedMembers.find(member => member.id === selectedId) || sortedMembers[0]
  const download = (member: Member) => { const popup = window.open('', '_blank'); if (!popup) { setError('Allow pop-ups for this site, then try Download card again.'); return }; popup.document.open(); popup.document.write(membershipCardDocument(member)); popup.document.close(); const images = [...popup.document.images]; void Promise.all(images.map(image => image.complete ? Promise.resolve() : new Promise<void>(resolve => { image.onload = () => resolve(); image.onerror = () => resolve() }))).then(() => { if (!popup.closed) { popup.focus(); popup.print() } }) }

  return <section className="soft-card admin-membership-cards mt-6" aria-labelledby="admin-membership-cards-title"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="icon-box shrink-0"><CreditCard size={20} /></span><div><p className="eyebrow">Membership</p><h2 id="admin-membership-cards-title" className="mt-1 text-2xl font-black">YDM membership cards</h2><p className="mt-1 text-sm text-slate-500">Create a print-ready identity card for any saved YDM member.</p></div></div><button type="button" onClick={() => void refresh()} disabled={loading} className="secondary-dark-btn disabled:cursor-not-allowed disabled:opacity-60"><RefreshCw size={17} /> Refresh members</button></div>{error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading ? <p role="status" className="mt-6 text-sm text-slate-500">Loading saved members…</p> : !sortedMembers.length ? <p className="mt-6 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-6 text-sm text-slate-600">No saved members available yet.</p> : <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(240px,320px)_minmax(0,1fr)]"><label className="field-label">Choose member<select className="field" value={selected?.id || ''} onChange={event => setSelectedId(event.target.value)}>{sortedMembers.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select><span className="mt-1 font-normal normal-case tracking-normal text-slate-500">The card uses the saved name, role, seniority, gender and profile photo.</span></label>{selected && <div className="min-w-0"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-slate-50 p-4" tabIndex={0} aria-label="Membership card preview. Scroll horizontally to see the full card."><style>{cardCss}</style><div dangerouslySetInnerHTML={{ __html: membershipCardMarkup(selected) }} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Choose “Save as PDF” in the print dialog. Print at 85.6 × 54 mm for standard ID card size.</p><button type="button" onClick={() => download(selected)} className="primary-btn"><Download size={17} /> Download card</button></div></div>}</div>}</section>
}
