import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CalendarDays, Download, Image, RefreshCw, Users } from 'lucide-react'
import { getAttendance, getGallery, getMembers, getProgramPoints, getWeeklyPrograms } from '../data/api'
import { downloadHtmlPdf } from '../data/pdf'
import type { AttendanceRecord, GalleryPhoto, Member, ProgramPoint, WeeklyProgram } from '../data/memberStore'
import ydmLogo from '../assets/jsc-ydm-logo-certificate.png'

type Language = 'en' | 'ta'
type Section = { title: string; paragraphs: string[] }
const todayYear = String(new Date().getFullYear())
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character] || character)
const unique = (items: string[]) => [...new Set(items.map(item => item.trim()).filter(Boolean))]
const list = (items: string[], fallback: string) => items.length ? items.join(', ') : fallback

export default function AdminYearlyReport() {
  const [year, setYear] = useState(todayYear)
  const [language, setLanguage] = useState<Language>('en')
  const [members, setMembers] = useState<Member[]>([])
  const [records, setRecords] = useState<AttendanceRecord[]>([])
  const [points, setPoints] = useState<ProgramPoint[]>([])
  const [gallery, setGallery] = useState<GalleryPhoto[]>([])
  const [weekly, setWeekly] = useState<WeeklyProgram[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [status, setStatus] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [m, a, p, g, w] = await Promise.all([getMembers(), getAttendance(), getProgramPoints(), getGallery(), getWeeklyPrograms(true)]); setMembers(m); setRecords(a); setPoints(p); setGallery(g); setWeekly(w) } catch { setError('Could not load the yearly report data. Please refresh and try again.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])

  const data = useMemo(() => {
    const prefix = `${year}-`
    const yearRecords = records.filter(item => item.date.startsWith(prefix))
    const yearPoints = points.filter(item => item.date.startsWith(prefix))
    const yearGallery = gallery.filter(item => item.date.startsWith(prefix))
    const yearWeekly = weekly.filter(item => item.date.startsWith(prefix))
    const meetingDates = unique(yearRecords.map(item => item.date))
    const present = yearRecords.filter(item => item.present).length
    const absent = yearRecords.length - present
    const rate = yearRecords.length ? Math.round((present / yearRecords.length) * 100) : 0
    const leaders = members.filter(item => { const role = item.role.toLowerCase(); return role && !role.includes('member') && !role.includes('children') })
    const participants = new Set([...yearRecords.map(item => item.memberId), ...yearPoints.map(item => item.memberId), ...yearWeekly.map(item => item.memberId)]).size
    const programNames = unique(yearPoints.map(item => item.program))
    const weeklyNames = unique(yearWeekly.map(item => item.programName))
    const eventNames = unique(yearGallery.map(item => item.description))
    const answers = yearPoints.reduce((sum, item) => sum + item.questionsAnswered, 0)
    return { yearRecords, yearPoints, yearGallery, yearWeekly, meetingDates, present, absent, rate, leaders, participants, programNames, weeklyNames, eventNames, answers }
  }, [year, records, points, gallery, weekly, members])

  const copy = useMemo(() => {
    const leaderList = list(data.leaders.map(member => `${member.name} (${member.role})`), language === 'en' ? 'the Pastor, YDM President, advisors and ministry team' : 'போதகர், YDM தலைவர், ஆலோசகர்கள் மற்றும் ஊழியக் குழுவினர்')
    const programs = list(data.programNames, language === 'en' ? 'Bible Quiz, Bible Reference and Song Survey' : 'வேதாகம வினாடி வினா, வேதாகம குறிப்பு மற்றும் பாடல் ஆய்வு')
    const weeklyPrograms = list(data.weeklyNames, language === 'en' ? 'weekly worship, prayer and fellowship gatherings' : 'வாராந்திர ஆராதனை, ஜெபம் மற்றும் ஐக்கியக் கூடுகைகள்')
    const events = list(data.eventNames, language === 'en' ? 'the fellowship and ministry events recorded during the year' : 'ஆண்டில் பதிவு செய்யப்பட்ட ஐக்கிய மற்றும் ஊழிய நிகழ்வுகள்')
    if (language === 'ta') return {
      eyebrow: 'ஆண்டு ஊழிய மதிப்பாய்வு', title: `JSC YDM ஆண்டு அறிக்கை · ${year}`, intro: 'ஆராதனை, ஜெபம், வேதவசனம், ஐக்கியம், சீஷத்துவம் மற்றும் சேவையின் விரிவான ஆவிக்குரிய பதிவு.', overview: 'ஆண்டின் சுருக்கம்', meetings: 'கூடுகை நாட்கள்', attendance: 'வருகைப் பதிவுகள்', questions: 'நிகழ்ச்சி பதில்கள்', events: 'படத்தொகுப்பு நிகழ்வுகள்', programs: 'வாராந்திர நிகழ்ச்சிகள்', leaders: 'தலைவர்கள்', download: 'விரிவான PDF பதிவிறக்கவும்', languageLabel: 'English', preparing: 'விரிவான ஆண்டு அறிக்கை தயாராகிறது…',
      verses: ['“அப்போஸ்தலருடைய உபதேசத்திலும், ஐக்கியத்திலும், அப்பம் பிட்குதலிலும், ஜெபங்களிலும் உறுதியாய்த் தரித்திருந்தார்கள்.” — அப்போஸ்தலர் 2:42', '“பலத்தினாலும் அல்ல, பராக்கிரமத்தினாலும் அல்ல, என்னுடைய ஆவியினாலேயே ஆகும்.” — சகரியா 4:6', '“நீங்கள் உலகத்திற்கு வெளிச்சமாயிருக்கிறீர்கள்.” — மத்தேயு 5:14'],
      pageOne: [
        { title: '1. தேவனுக்கு ஸ்தோத்திரமும் ஊழிய நோக்கமும்', paragraphs: [`${year} ஆம் ஆண்டு முழுவதும் Youth Divine Movement ஊழியத்தை கிருபையால் தாங்கி, பாதுகாத்து, வழிநடத்திய சர்வவல்லமையுள்ள தேவனுக்கு நன்றியையும் மகிமையையும் செலுத்துகிறோம். இயேசு கிறிஸ்துவை மையமாகக் கொண்டு, பரிசுத்த ஆவியின் வல்லமையில் இளைஞர்களை ஜெபம், வேதவசனம், பரிசுத்த வாழ்க்கை மற்றும் சபை சேவையில் வளர்ப்பதே எங்கள் நோக்கமாக இருந்தது.`, `இந்த அறிக்கை எண்களின் தொகுப்பு மட்டும் அல்ல. ஒவ்வொரு வருகைப் பதிவிற்குப் பின்னாலும் ஒரு இளைஞரின் விசுவாசப் பயணமும், ஒவ்வொரு நிகழ்ச்சிக்குப் பின்னாலும் பலரின் ஜெபமும் அர்ப்பணிப்பும் உள்ளன. தேவன் செய்த நன்மைகளை நினைவுகூர்ந்து, வருகிற காலத்திற்கு விசுவாசத்தோடு முன்னேற இந்த பதிவு உதவுகிறது.`] },
        { title: '2. உறுப்பினர்கள் மற்றும் ஆவிக்குரிய தலைமை', paragraphs: [`இந்த ஆண்டில் YDM குடும்பத்தில் ${members.length} உறுப்பினர்கள் பதிவு செய்யப்பட்டுள்ளனர்; ${data.participants} பேர் வருகை, வேதாகம நிகழ்ச்சி அல்லது வாராந்திர ஊழியத்தில் நேரடியாக பங்கேற்றுள்ளனர். குழந்தைகள், இளையோர், மூத்தோர் மற்றும் பொறுப்பாளர்கள் ஒரே கிறிஸ்துவின் சரீரமாக இணைந்து வளர்ந்தனர்.`, `${leaderList} ஆகியோரின் ஜெபமுள்ள தலைமை, ஆலோசனை மற்றும் தன்னலமற்ற சேவைக்காக நன்றி செலுத்துகிறோம். தலைமை என்பது பதவி மட்டுமல்ல; வசனத்தில் முன்மாதிரியாக இருந்து, இளைஞர்களைக் கேட்டு, ஊக்குவித்து, தேவனுடைய அழைப்பை உணர உதவும் ஆவிக்குரிய பொறுப்பு என்பதை இந்த ஆண்டு மீண்டும் வெளிப்படுத்தியது.`] },
        { title: '3. வருகை, ஐக்கியம் மற்றும் மேய்ப்புப் பராமரிப்பு', paragraphs: [`${data.meetingDates.length} கூடுகை நாட்களில் ${data.yearRecords.length} வருகைப் பதிவுகள் செய்யப்பட்டுள்ளன. அவற்றில் ${data.present} வருகைகளும் ${data.absent} வராத பதிவுகளும் உள்ளன; பதிவுசெய்யப்பட்ட வருகை விகிதம் ${data.rate}% ஆகும். இந்தத் தகவல் குற்றம்சாட்டுவதற்கல்ல; தொடர்ச்சியான பங்கேற்பை ஊக்குவிக்கவும், ஆதரவு தேவைப்படுகிறவர்களை ஜெபத்தோடு அணுகவும் பயன்படுகிறது.`, `ஒவ்வொரு கூடுகையும் பாடல்கள், சாட்சிகள், ஜெபம், வேதவசன தியானம் மற்றும் அன்பின் ஐக்கியத்திற்கான இடமாக இருந்தது. தவறாமல் வந்தவர்களின் விசுவாசத்திற்கும், இடையூறுகளுக்குப் பிறகும் மீண்டும் இணைந்தவர்களின் மனஉறுதிக்கும் தேவனை ஸ்தோத்திரிக்கிறோம். அடுத்த ஆண்டில் தனிப்பட்ட தொடர்பு, குடும்ப ஆதரவு மற்றும் மேய்ப்புப் பராமரிப்பை மேலும் வலுப்படுத்துவது முக்கிய நோக்கமாகும்.`] },
      ] as Section[],
      pageTwo: [
        { title: '4. வேதாகமக் கற்றல் மற்றும் திறன் வளர்ச்சி', paragraphs: [`${programs} போன்ற நிகழ்ச்சிகளில் ${data.yearPoints.length} பதிவுகள் மூலம் மொத்தம் ${data.answers} பதில்கள் பதிவு செய்யப்பட்டுள்ளன. இவை போட்டிக்காக மட்டுமல்லாமல், வசனத்தை வாசிக்க, நினைவில் கொள்ள, சரியாகப் புரிந்துகொள்ள மற்றும் வாழ்க்கையில் நடைமுறைப்படுத்த இளைஞர்களைத் தூண்டின.`, `ஒவ்வொரு முயற்சியும் தேவனுடைய வார்த்தைக்கான பசியை வளர்க்கும் விதையாகும். பதிலளித்தவர்கள், கற்றுக்கொடுத்தவர்கள், கேள்விகளைத் தயாரித்தவர்கள் மற்றும் ஊக்குவித்த பெற்றோர்கள் அனைவருக்கும் நன்றி. வருகிற ஆண்டில் ஒவ்வொரு வயது பிரிவுக்கும் திட்டமிட்ட வேதாகமப் பயிற்சி, ஜெபப் பங்காளித்துவம் மற்றும் திறன் வழிகாட்டுதல் வழங்கப்பட வேண்டும்.`] },
        { title: '5. வாராந்திர ஊழியம் மற்றும் நிகழ்வுச் சாட்சிகள்', paragraphs: [`${data.yearWeekly.length} வாராந்திர சேவைப் பதிவுகள் செய்யப்பட்டுள்ளன. அவற்றில் ${weeklyPrograms} இடம்பெற்றன. பல இளைஞர்கள் பாடல், வசன வாசிப்பு, ஜெபம், சாட்சி மற்றும் ஒழுங்கமைப்பு போன்ற பொறுப்புகளை ஏற்று, தங்களுக்குக் கொடுக்கப்பட்ட வரங்களை தேவனுடைய மகிமைக்காக பயன்படுத்தினர்.`, `படத்தொகுப்பில் ${data.yearGallery.length} நிகழ்வுகள் பதிவு செய்யப்பட்டுள்ளன. ${events} போன்ற நினைவுகள் சபையின் ஐக்கியத்தையும், இளைஞர்களின் சந்தோஷமான பங்கேற்பையும், தேவன் கொடுத்த வாய்ப்புகளையும் சாட்சியாகக் காக்கின்றன. ஒவ்வொரு படமும் ஒரு நிகழ்வை மட்டுமல்ல, தேவ கிருபையின் நினைவையும் வெளிப்படுத்துகிறது.`] },
        { title: '6. நன்றி, ஆவிக்குரிய சிந்தனை மற்றும் அடுத்த ஆண்டு அழைப்பு', paragraphs: [`போதகர், YDM தலைவர், ஆலோசகர்கள், நிர்வாகிகள், ஆசிரியர்கள், பெற்றோர்கள், சபை விசுவாசிகள் மற்றும் ஒவ்வொரு இளைஞரின் ஜெபம், நேரம், திறமை மற்றும் ஆதரவிற்காக மனமார்ந்த நன்றி. காணப்படாத பல சேவைகளும் தேவனுடைய பார்வையில் மதிப்புள்ளவையே. எல்லா மகிமையும் இயேசு கிறிஸ்துவுக்கே உரியது.`, `அடுத்த ஆண்டில் பரிசுத்த ஆவியின் அபிஷேகம், ஆழமான ஜெப வாழ்க்கை, சத்திய வசனத்தின் தெளிவு, தூய சாட்சி, பரிவுள்ள சேவை மற்றும் சுவிசேஷ தைரியம் ஆகியவற்றில் வளர தீர்மானிக்கிறோம். ஒவ்வொரு இளைஞரும் கிறிஸ்துவில் வேரூன்றி, சபையில் பொறுப்புடன் சேவை செய்து, உலகத்தில் வெளிச்சமாக வாழ தேவன் கிருபை செய்வாராக. ஆமென்.`] },
      ] as Section[],
    }
    return {
      eyebrow: 'Ministry year review', title: `JSC YDM Yearly Report · ${year}`, intro: 'A detailed spiritual record of worship, prayer, Scripture, fellowship, discipleship and service.', overview: 'Year at a glance', meetings: 'Meeting days', attendance: 'Attendance records', questions: 'Program answers', events: 'Gallery events', programs: 'Weekly programs', leaders: 'Leaders', download: 'Download detailed PDF', languageLabel: 'தமிழ்', preparing: 'Preparing detailed yearly report…',
      verses: ['“And they continued steadfastly in the apostles’ doctrine and fellowship, and in breaking of bread, and in prayers.” — Acts 2:42', '“Not by might, nor by power, but by my spirit, saith the Lord of hosts.” — Zechariah 4:6', '“Ye are the light of the world.” — Matthew 5:14'],
      pageOne: [
        { title: '1. Thanksgiving and ministry vision', paragraphs: [`We begin this ${year} report by giving all glory, honour and thanksgiving to Almighty God, who sustained, protected and guided the Youth Divine Movement throughout the year. Our ministry purpose remained clear: to help young people know Jesus Christ personally, grow in the Word of God, develop a Spirit-filled prayer life, walk in holiness and serve faithfully in the local church.`, `This document is more than a collection of numbers. Behind every attendance entry is a young person’s journey of faith, and behind every program is the prayer, preparation and service of many people. We record these details so that we may remember the goodness of God, recognise areas of growth and move into the coming year with humility, wisdom and expectation.`] },
        { title: '2. Membership and spiritual leadership', paragraphs: [`The YDM family included ${members.length} saved members during the year, with ${data.participants} people participating through attendance, Bible programs or weekly ministry assignments. Kutties, Juniors, Seniors and office holders were encouraged to grow together as one body in Christ, honouring one another’s gifts and learning to carry responsibility with joy.`, `We gratefully recognise the prayerful leadership of ${leaderList}. Their counsel, encouragement and practical service helped create a safe place where young people could ask questions, discover their gifts and understand God’s calling. Leadership was treated not merely as a title, but as a spiritual responsibility to model faith, listen with compassion and point every member toward Christ.`] },
        { title: '3. Attendance, fellowship and pastoral care', paragraphs: [`Across ${data.meetingDates.length} recorded meeting days, the ministry saved ${data.yearRecords.length} attendance entries: ${data.present} present records and ${data.absent} absences. This produces a recorded attendance rate of ${data.rate}%. These figures are not used to condemn anyone; they help leaders encourage consistency, recognise faithful participation and prayerfully support members who may be facing practical or spiritual challenges.`, `Each gathering provided space for worship, testimony, prayer, Scripture meditation and loving fellowship. We thank God for those who attended faithfully and for those who returned after interruptions. In the coming year, stronger personal follow-up, family partnership and pastoral care should help every member feel known, valued and spiritually supported.`] },
      ] as Section[],
      pageTwo: [
        { title: '4. Biblical learning and development', paragraphs: [`Through programs including ${programs}, the database contains ${data.yearPoints.length} participation records and ${data.answers} total answers. These activities were not conducted only for competition. They encouraged young people to read Scripture carefully, remember biblical truth, understand its meaning and apply the Word of God in daily decisions.`, `Every sincere attempt represents a seed of hunger for God’s Word. We thank the participants, teachers, question preparers and parents who encouraged learning. The next year should build on this foundation through structured Bible study for every age group, prayer partnerships, mentoring and opportunities to communicate Scripture with clarity and confidence.`] },
        { title: '5. Weekly ministry and event testimonies', paragraphs: [`The ministry recorded ${data.yearWeekly.length} weekly service assignments, including ${weeklyPrograms}. Young people accepted responsibility in singing, Scripture reading, prayer, testimony and coordination. These opportunities helped members move from observation to participation and use their God-given gifts for the glory of Jesus Christ.`, `The gallery preserves ${data.yearGallery.length} event records, including ${events}. These photographs and descriptions bear witness to fellowship, joyful participation and doors of opportunity opened by God. Each documented event is more than a memory; it is a reminder that the Lord builds His people through shared worship, service and encouragement.`] },
        { title: '6. Thanksgiving, spiritual reflection and the call ahead', paragraphs: [`We sincerely thank our Pastor, YDM President, advisors, office bearers, teachers, parents, church believers and every young person who offered prayer, time, talent and support. Many acts of service were performed quietly and may never appear in a database, yet they are seen and valued by God. All honour for every good result belongs to Jesus Christ alone.`, `Looking ahead, we commit ourselves to seek a fresh anointing of the Holy Spirit, deeper prayer, sound biblical understanding, holy character, compassionate service and courage in the Gospel. May every young person become rooted in Christ, dependable in the church and a light in the community. May the Lord establish the work of our hands and lead the Youth Divine Movement from glory to glory. Amen.`] },
      ] as Section[],
    }
  }, [language, year, data, members.length])

  const years = [...new Set([todayYear, ...records, ...points, ...gallery, ...weekly].map(item => typeof item === 'string' ? item : item.date.slice(0, 4)))].sort().reverse()
  const stats = [[CalendarDays, copy.meetings, data.meetingDates.length], [Users, copy.attendance, data.yearRecords.length], [BookOpen, copy.questions, data.answers], [Image, copy.events, data.yearGallery.length], [CalendarDays, copy.programs, data.yearWeekly.length], [Users, copy.leaders, data.leaders.length]] as const
  const sectionHtml = (section: Section) => `<section><h2>${escapeHtml(section.title)}</h2>${section.paragraphs.map(paragraph => `<p>${escapeHtml(paragraph)}</p>`).join('')}</section>`
  const reportDocument = () => `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#e9eee9;color:#172b24;font-family:Arial,sans-serif}.report-page{position:relative;width:794px;min-height:1120px;padding:58px 66px;background:#fff;break-after:page}.report-page:last-child{break-after:auto}.report-page:before{content:'';position:absolute;inset:20px;border:1px solid #d9c384;pointer-events:none}.report-header{display:flex;align-items:center;gap:18px;padding-bottom:22px;border-bottom:2px solid #087f5b}.report-header img{width:74px;height:74px;object-fit:contain}.eyebrow{color:#087f5b;font-size:11px;font-weight:900;letter-spacing:2px;text-transform:uppercase}h1{margin:6px 0 0;font:700 30px Georgia,serif;color:#071f19}.intro{margin:9px 0 0;color:#587066;font-size:13px;line-height:1.5}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:22px 0}.stat{padding:12px;border:1px solid #dce9e3;border-radius:10px;background:#f3f8f5}.stat-label{color:#587066;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px}.stat-value{margin-top:4px;color:#087f5b;font-size:22px;font-weight:900}section{margin-top:22px}h2{margin:0 0 10px;padding-bottom:7px;border-bottom:1px solid #d8e6df;color:#087f5b;font:700 19px Georgia,serif}p{margin:0 0 11px;font-size:13px;line-height:1.65;text-align:justify}.verse{margin:20px 0 0;padding:15px 18px;border-left:5px solid #e3bc62;background:#e8f5ef;color:#164f3d;font:italic 14px/1.6 Georgia,serif}.page-number{position:absolute;right:46px;bottom:34px;color:#8a9d95;font-size:10px}.closing{margin-top:20px;padding:14px;border:1px solid #ead8a3;border-radius:12px;background:#fffbef;color:#6b5217;text-align:center;font:700 13px Georgia,serif}</style></head><body><article class="report-page"><header class="report-header"><img src="${escapeHtml(ydmLogo)}" alt="YDM logo"><div><div class="eyebrow">${escapeHtml(copy.eyebrow)}</div><h1>${escapeHtml(copy.title)}</h1><p class="intro">${escapeHtml(copy.intro)}</p></div></header><div class="stats">${stats.map(([, label, value]) => `<div class="stat"><div class="stat-label">${escapeHtml(String(label))}</div><div class="stat-value">${value}</div></div>`).join('')}</div><div class="verse">${escapeHtml(copy.verses[0])}</div>${copy.pageOne.map(sectionHtml).join('')}<div class="page-number">1 / 2</div></article><article class="report-page"><header class="report-header"><img src="${escapeHtml(ydmLogo)}" alt="YDM logo"><div><div class="eyebrow">${escapeHtml(copy.eyebrow)}</div><h1>${escapeHtml(copy.title)}</h1><p class="intro">${escapeHtml(copy.intro)}</p></div></header><div class="verse">${escapeHtml(copy.verses[1])}</div>${copy.pageTwo.map(sectionHtml).join('')}<div class="verse">${escapeHtml(copy.verses[2])}</div><div class="closing">Jehovah Salvation Church · Youth Divine Movement · JSC Kollemcode</div><div class="page-number">2 / 2</div></article></body></html>`
  const download = async () => { setStatus(language === 'en' ? 'Creating detailed yearly report PDF…' : 'விரிவான ஆண்டு அறிக்கை PDF உருவாக்கப்படுகிறது…'); try { await downloadHtmlPdf(reportDocument(), `jsc-ydm-yearly-report-${year}-${language}.pdf`); setStatus(language === 'en' ? 'Detailed yearly report PDF downloaded.' : 'விரிவான ஆண்டு அறிக்கை PDF பதிவிறக்கப்பட்டது.') } catch { setStatus(language === 'en' ? 'The PDF could not be created. Please try again.' : 'PDF உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.') } }

  return <section className="soft-card admin-yearly-report" aria-labelledby="admin-yearly-report-title"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="icon-box"><BookOpen size={20} /></span><div><p className="eyebrow">{copy.eyebrow}</p><h2 id="admin-yearly-report-title" className="mt-1 text-2xl font-black">{copy.title}</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">{copy.intro}</p></div></div><div className="flex flex-wrap gap-2"><select aria-label="Report year" className="field" value={year} onChange={event => setYear(event.target.value)}>{years.map(value => <option key={value} value={value}>{value}</option>)}</select><button type="button" className="secondary-dark-btn" onClick={() => setLanguage(current => current === 'en' ? 'ta' : 'en')}>{copy.languageLabel}</button><button type="button" className="secondary-dark-btn" onClick={() => void load()} disabled={loading}><RefreshCw size={17} /> Refresh</button><button type="button" className="primary-btn" onClick={() => void download()} disabled={loading || Boolean(error)}><Download size={17} /> {copy.download}</button></div></div>{error && <p role="alert" className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading ? <p role="status" className="mt-6 text-sm text-slate-500">{copy.preparing}</p> : !error && <><h3 className="mt-7 text-lg font-black">{copy.overview}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stats.map(([Icon, label, value]) => <div key={String(label)} className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4"><Icon size={18} className="text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{String(label)}</p><p className="mt-1 text-3xl font-black text-slate-900">{String(value)}</p></div>)}</div><div className="mt-7 grid gap-4 lg:grid-cols-2">{[...copy.pageOne, ...copy.pageTwo].map(section => <article key={section.title} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-serif text-lg font-bold text-emerald-900">{section.title}</h3>{section.paragraphs.map(paragraph => <p key={paragraph} className="mt-3 text-sm leading-7 text-slate-600">{paragraph}</p>)}</article>)}</div><div className="mt-5 rounded-2xl border-l-4 border-[#e3bc62] bg-[#e8f5ef] p-5"><p className="font-serif text-sm italic leading-7 text-emerald-950">{copy.verses.join('  ·  ')}</p></div></>}{status && <p role="status" className="mt-4 text-sm font-semibold text-emerald-800">{status}</p>}</section>
}
