import { useEffect, useState } from 'react'
import { getMembers, getProgramPoints, saveProgramPoint } from '../data/api'
import { Member, ProgramPoint } from '../data/memberStore'
import { programs as allPrograms } from '../data/siteData'

const pointPrograms = ['Bible Reference', 'Bible Quiz', 'Song Survey']
const programs = pointPrograms.map((title, index) => ({ id: index + 1, title }))

export default function AdminProgramPoints() {
  const [members, setMembers] = useState<Member[]>([]); const [points, setPoints] = useState<ProgramPoint[]>([]); const [memberId, setMemberId] = useState(''); const [program, setProgram] = useState(pointPrograms[0]); const [date, setDate] = useState(''); const [questionsAnswered, setQuestionsAnswered] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { void Promise.all([getMembers(), getProgramPoints()]).then(([m, p]) => { setMembers(m); setPoints(p) }).catch(() => setMessage('Could not load program points.')) }, [])
  const save = async () => { const member = members.find(item => item.id === memberId); const answered = Number(questionsAnswered); if (!member || !date || !Number.isInteger(answered) || answered < 0 || answered > 5) { setMessage('Select a member, date, and questions answered from 0 to 5.'); return } const item: ProgramPoint = { id: crypto.randomUUID(), memberId, name: member.name, program, seniority: member.seniority, date, questionsAnswered: answered }; try { await saveProgramPoint(item); setPoints(current => [item, ...current]); setQuestionsAnswered(''); setMessage('Program point saved.') } catch { setMessage('Could not save program point.') } }
  return <section className="soft-card mt-6"><h2 className="font-black">Program points</h2><p className="mt-1 text-sm text-slate-500">Record member name, program, seniority, and questions answered out of 5.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><select className="field" value={memberId} onChange={event => setMemberId(event.target.value)}><option value="">Select member</option>{members.map(member => <option key={member.id} value={member.id}>{member.name} · {member.seniority || 'Member'}</option>)}</select><select className="field" value={program} onChange={event => setProgram(event.target.value)}>{programs.map(item => <option key={item.id}>{item.title}</option>)}</select><input className="field" type="date" value={date} onChange={event => setDate(event.target.value)} /><div className="flex gap-2"><input className="field" type="number" min="0" max="5" value={questionsAnswered} onChange={event => setQuestionsAnswered(event.target.value)} placeholder="Questions answered (0–5)" /><button className="primary-btn shrink-0" onClick={() => void save()}>Save</button></div></div>{message && <p className="mt-3 text-sm text-emerald-700">{message}</p>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-2">Member</th><th>Seniority</th><th>Program</th><th>Date</th><th>Questions answered</th></tr></thead><tbody className="divide-y divide-slate-100">{points.map(point => <tr key={point.id}><td className="py-3 font-bold">{point.name}</td><td>{point.seniority || '—'}</td><td>{point.program}</td><td>{point.date}</td><td className="font-black">{point.questionsAnswered}/5</td></tr>)}</tbody></table></div></section>
}
