import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CalendarDays, Download, Image, RefreshCw, Users } from 'lucide-react'
import { getAttendance, getGallery, getMembers, getProgramPoints, getWeeklyPrograms } from '../data/api'
import type { AttendanceRecord, GalleryPhoto, Member, ProgramPoint, WeeklyProgram } from '../data/memberStore'

const todayYear = String(new Date().getFullYear())
const verse = 'And they continued steadfastly in the apostles’ doctrine and fellowship, and in breaking of bread, and in prayers. — Acts 2:42'
const tamilVerse = 'அப்போஸ்தலருடைய உபதேசத்திலும், ஐக்கியத்திலும், அப்பம் பிட்குதலிலும், ஜெபங்களிலும் உறுதியாகத் தரித்திருந்தார்கள். — அப்போஸ்தலர் 2:42'

export default function AdminYearlyReport() {
  const [year, setYear] = useState(todayYear); const [language, setLanguage] = useState<'en' | 'ta'>('en')
  const [members, setMembers] = useState<Member[]>([]); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [points, setPoints] = useState<ProgramPoint[]>([]); const [gallery, setGallery] = useState<GalleryPhoto[]>([]); const [weekly, setWeekly] = useState<WeeklyProgram[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [m, a, p, g, w] = await Promise.all([getMembers(), getAttendance(), getProgramPoints(), getGallery(), getWeeklyPrograms(true)]); setMembers(m); setRecords(a); setPoints(p); setGallery(g); setWeekly(w) } catch { setError('Could not load the yearly report data. Please refresh and try again.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const data = useMemo(() => { const prefix = `${year}-`; const yearRecords = records.filter(item => item.date.startsWith(prefix)); const yearPoints = points.filter(item => item.date.startsWith(prefix)); const yearGallery = gallery.filter(item => item.date.startsWith(prefix)); const yearWeekly = weekly.filter(item => item.date.startsWith(prefix)); const meetingDates = new Set(yearRecords.map(item => item.date)); const present = yearRecords.filter(item => item.present).length; const leaders = members.filter(item => { const role = item.role.toLowerCase(); return role && !role.includes('member') && !role.includes('children') }).length; return { yearRecords, yearPoints, yearGallery, yearWeekly, meetingDates, present, leaders } }, [year, records, points, gallery, weekly, members])
  const copy = language === 'en' ? { eyebrow: 'Ministry review', title: `JSC YDM Yearly Report · ${year}`, intro: 'A prayerful record of worship, fellowship, discipleship and service throughout the year.', overview: 'Year at a glance', meetings: 'Meeting dates', attendance: 'Attendance records', questions: 'Program answers', events: 'Gallery events', programs: 'Weekly programs', leaders: 'Leaders & office holders', reflection: 'Faith reflection', reflectionText: 'This year was built by faithful prayer, Scripture, fellowship and service. May the Holy Spirit continue to empower every young person to grow in Christ and serve the church with joy.', verse } : { eyebrow: 'ஊழிய ஆண்டு மதிப்பாய்வு', title: `JSC YDM ஆண்டு அறிக்கை · ${year}`, intro: 'ஆண்டு முழுவதும் நடைபெற்ற ஆராதனை, ஐக்கியம், சீஷத்துவம் மற்றும் சேவையின் ஜெபமுள்ள பதிவு.', overview: 'ஆண்டின் சுருக்கம்', meetings: 'கூட்ட நாட்கள்', attendance: 'வருகைப் பதிவுகள்', questions: 'நிரல் பதில்கள்', events: 'காட்சியக நிகழ்வுகள்', programs: 'வாராந்திர நிகழ்ச்சிகள்', leaders: 'தலைவர்கள் மற்றும் பொறுப்பாளர்கள்', reflection: 'விசுவாச சிந்தனை', reflectionText: 'இந்த ஆண்டு ஜெபம், வேதவசனம், ஐக்கியம் மற்றும் சேவையால் கட்டப்பட்டது. ஒவ்வொரு இளைஞரும் கிறிஸ்துவில் வளர்ந்து மகிழ்ச்சியுடன் சபைக்கு சேவை செய்ய பரிசுத்த ஆவியானவர் தொடர்ந்து வல்லமை அளிப்பாராக.', verse: tamilVerse }
  const print = () => { const html = `<html lang="${language === 'en' ? 'en' : 'ta'}"><head><meta charset="utf-8"><title>${copy.title}</title><style>body{font-family:Arial,sans-serif;color:#071f19;padding:28px}h1{color:#087f5b;font-size:28px}h2{color:#087f5b;border-bottom:1px solid #d4e6dc;padding-bottom:6px;margin-top:28px}.verse{background:#e8f5ef;border-left:5px solid #e3bc62;padding:16px;font-style:italic}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{background:#f3f7f5;padding:14px;border-radius:10px}.label{font-size:11px;color:#58766a;text-transform:uppercase}.value{font-size:25px;font-weight:bold;margin-top:5px}footer{margin-top:48px;display:flex;justify-content:space-between}</style></head><body><p>${copy.eyebrow}</p><h1>${copy.title}</h1><p>${copy.intro}</p><h2>${copy.overview}</h2><div class="stats">${[['${copy.meetings}', data.meetingDates.size],['${copy.attendance}', data.yearRecords.length],['${copy.questions}', data.yearPoints.reduce((sum, item) => sum + item.questionsAnswered, 0)],['${copy.events}', data.yearGallery.length],['${copy.programs}', data.yearWeekly.length],['${copy.leaders}', data.leaders]].map(([label, value]) => `<div class="stat"><div class="label">${label}</div><div class="value">${value}</div></div>`).join('')}</div><h2>${copy.reflection}</h2><p>${copy.reflectionText}</p><p class="verse">${copy.verse}</p><footer><span>YDM President Signature</span><span>Church Pastor Signature</span></footer></body></html>`; const popup = window.open('', '_blank'); if (!popup) return; popup.document.write(html); popup.document.close(); setTimeout(() => { popup.focus(); popup.print() }, 150) }
  const reportStats = [[CalendarDays, copy.meetings, data.meetingDates.size], [Users, copy.attendance, data.yearRecords.length], [BookOpen, copy.questions, data.yearPoints.reduce((sum, item) => sum + item.questionsAnswered, 0)], [Image, copy.events, data.yearGallery.length], [CalendarDays, copy.programs, data.yearWeekly.length], [Users, copy.leaders, data.leaders]] as const
  return <section className="soft-card admin-yearly-report" aria-labelledby="admin-yearly-report-title"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="icon-box"><BookOpen size={20} /></span><div><p className="eyebrow">{copy.eyebrow}</p><h2 id="admin-yearly-report-title" className="mt-1 text-2xl font-black">{copy.title}</h2><p className="mt-1 text-sm text-slate-500">{copy.intro}</p></div></div><div className="flex flex-wrap gap-2"><select aria-label="Report year" className="field" value={year} onChange={event => setYear(event.target.value)}><option value={todayYear}>{todayYear}</option>{[...new Set([...records, ...points, ...gallery, ...weekly].map(item => item.date.slice(0, 4)))].filter(value => value !== todayYear).sort().reverse().map(value => <option key={value} value={value}>{value}</option>)}</select><button type="button" className="secondary-dark-btn" onClick={() => setLanguage(current => current === 'en' ? 'ta' : 'en')}>{language === 'en' ? 'தமிழ்' : 'English'}</button><button type="button" className="secondary-dark-btn" onClick={() => void load()} disabled={loading}><RefreshCw size={17} /> Refresh</button><button type="button" className="primary-btn" onClick={print} disabled={loading}><Download size={17} /> Download / Print</button></div></div>{error && <p role="alert" className="mt-5 text-sm text-rose-700">{error}</p>}{loading ? <p role="status" className="mt-6 text-sm text-slate-500">Preparing yearly report...</p> : <><h3 className="mt-7 text-lg font-black">{copy.overview}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{reportStats.map(([Icon, label, value]) => <div key={String(label)} className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4"><Icon size={18} className="text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{String(label)}</p><p className="mt-1 text-3xl font-black text-slate-900">{String(value)}</p></div>)}</div><div className="mt-7 rounded-2xl border-l-4 border-[#e3bc62] bg-[#e8f5ef] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">{copy.reflection}</p><p className="mt-2 text-sm leading-7 text-slate-700">{copy.reflectionText}</p><p className="mt-4 font-serif text-sm italic text-emerald-950">{copy.verse}</p></div></>}</section>
}
