import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Trash2 } from 'lucide-react'
import { createWeeklyProgram, deleteWeeklyProgram, getMembers, getWeeklyPrograms } from '../data/api'
import { Member, WeeklyProgram } from '../data/memberStore'

const today = new Date().toISOString().slice(0, 10)
const byDate = (items: WeeklyProgram[]) => Array.from(new Map(items.map(item => [item.id, item])).values()).sort((a, b) => b.date.localeCompare(a.date) || a.serialNo - b.serialNo)
const prettyDate = (date: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(`${date}T00:00:00`))

export function WeeklyProgramPublic() {
  const [items, setItems] = useState<WeeklyProgram[]>([])
  useEffect(() => { const load = () => { void getWeeklyPrograms().then(setItems).catch(() => setItems([])) }; load(); const timer = window.setInterval(load, 30_000); return () => window.clearInterval(timer) }, [])
  const groups = useMemo(() => Array.from(new Map(byDate(items).map(item => [item.date, byDate(items).filter(row => row.date === item.date)])).entries()), [items])
  if (!groups.length) return null
  return <section className="weekly-program-section mt-12"><div className="mb-5"><p className="eyebrow">Weekly program</p><h2 className="mt-2 text-3xl font-black">This week’s program</h2></div><div className="grid gap-5">{groups.map(([date, rows]) => <article key={date} className="soft-card overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><span className="icon-box"><CalendarDays size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Date</p><h3 className="text-xl font-black">{prettyDate(date)}</h3></div></div><div className="overflow-x-auto"><table className="mt-3 w-full min-w-[520px] text-left"><thead className="text-xs uppercase tracking-[.12em] text-slate-500"><tr><th className="py-3">Sl.No</th><th>Program Name</th><th>Member Name</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.id}><td className="py-3 font-bold">{row.serialNo}</td><td>{row.programName}</td><td>{row.memberName}</td></tr>)}</tbody></table></div></article>)}</div></section>
}

export default function AdminWeeklyPrograms() {
  const [members, setMembers] = useState<Member[]>([]); const [items, setItems] = useState<WeeklyProgram[]>([]); const [date, setDate] = useState(today); const [serialNo, setSerialNo] = useState(''); const [programName, setProgramName] = useState(''); const [memberId, setMemberId] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { void Promise.all([getMembers(), getWeeklyPrograms(true)]).then(([savedMembers, savedItems]) => { setMembers(savedMembers); setItems(byDate(savedItems)) }).catch(() => setMessage('Could not load weekly programs.')) }, [])
  const save = async () => { const member = members.find(item => item.id === memberId); const number = Number(serialNo); if (!date || !programName.trim() || !member || !Number.isInteger(number) || number < 1 || number > 15) { setMessage('Enter a date, serial number from 1 to 15, program name, and member.'); return }; if (items.filter(item => item.date === date).length >= 15) { setMessage('A date can contain a maximum of 15 rows.'); return }; if (items.some(item => item.date === date && item.serialNo === number)) { setMessage('That serial number already exists for this date.'); return }; const next: WeeklyProgram = { id: crypto.randomUUID(), date, serialNo: number, programName: programName.trim(), memberId, memberName: member.name }; try { await createWeeklyProgram(next); setItems(current => byDate([next, ...current])); setSerialNo(''); setProgramName(''); setMemberId(''); setMessage('Weekly program saved successfully.') } catch { setMessage('Could not save weekly program. Check the date and serial number.') } }
  const remove = async (id: string) => { try { await deleteWeeklyProgram(id); setItems(current => current.filter(item => item.id !== id)); setMessage('Weekly program deleted successfully.') } catch { setMessage('Could not delete weekly program.') } }
  const groups = useMemo(() => Array.from(new Map(byDate(items).map(item => [item.date, byDate(items).filter(row => row.date === item.date)])).entries()), [items])
  return <section className="soft-card mt-6"><div className="mb-5 flex items-center gap-3"><span className="icon-box"><CalendarDays size={19} /></span><div><p className="eyebrow">Weekly program</p><h2 className="mt-1 text-2xl font-black">Add weekly program</h2><p className="mt-1 text-sm text-slate-500">Add up to 15 program rows for each date.</p></div></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-[150px_110px_1fr_1fr_auto]"><label className="field-label">Date<input type="date" value={date} onChange={event => setDate(event.target.value)} className="field" /></label><label className="field-label">Sl.No<input type="number" min="1" max="15" value={serialNo} onChange={event => setSerialNo(event.target.value)} className="field" placeholder="1–15" /></label><label className="field-label">Program name<input value={programName} onChange={event => setProgramName(event.target.value)} className="field" placeholder="Program name" /></label><label className="field-label">Member name<select value={memberId} onChange={event => setMemberId(event.target.value)} className="field"><option value="">Select member</option>{members.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><button className="primary-btn self-end" onClick={() => void save()}>Save</button></div>{message && <p className="mt-3 text-sm text-emerald-700">{message}</p>}<div className="mt-6 grid gap-5 border-t border-slate-200 pt-5">{groups.map(([dateValue, rows]) => <div key={dateValue} className="overflow-x-auto"><h3 className="mb-2 font-black">{prettyDate(dateValue)}</h3><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-2">Sl.No</th><th>Program Name</th><th>Member Name</th><th className="text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.id}><td className="py-3 font-bold">{row.serialNo}</td><td>{row.programName}</td><td>{row.memberName}</td><td className="text-right"><button aria-label={`Delete weekly program ${row.programName}`} onClick={() => void remove(row.id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>)}{!groups.length && <p className="text-sm text-slate-500">No weekly programs added yet.</p>}</div></section>
}
